name: discord message
on:
  discussion:
    types: [created, edited, answered]
    category: Announcements
  discussion_comment:
    types: [created, deleted]
    category: Announcements
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "GitHub Bot"
        message: "A new commit has been pushed with custom color."
